# Generated by Django 2.1.4 on 2018-12-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default='15:00:00'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(),
        ),
    ]
