# Generated by Django 2.1.4 on 2019-01-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20181230_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.SlugField(default='hi'),
            preserve_default=False,
        ),
    ]
