# Generated by Django 2.1.4 on 2019-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league_slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
