# Generated by Django 2.1.5 on 2019-01-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_matchday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_goals_first_half',
            new_name='away_goals_fh',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_goals_first_half',
            new_name='home_goals_fh',
        ),
    ]
