# Generated by Django 2.1.5 on 2019-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20190120_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goals_sh',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals_sh',
            field=models.IntegerField(null=True),
        ),
    ]
