# Generated by Django 2.1.5 on 2019-01-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20190120_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_fh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_sh',
            field=models.IntegerField(null=True),
        ),
    ]
