# Generated by Django 2.1.5 on 2019-01-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_auto_20190120_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result_fh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_fh', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result_sh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_sh', to='teams.Team'),
        ),
    ]
