# Generated by Django 2.1.5 on 2019-01-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_auto_20190120_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_fh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_sh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
