# Generated by Django 2.1.5 on 2019-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_auto_20190122_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
    ]
