# Generated by Django 2.1.4 on 2018-12-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='league', to='leagues.League')),
            ],
        ),
    ]
