# Generated by Django 2.1.4 on 2018-12-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
    ]
