# Generated by Django 2.1.4 on 2019-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='hi'),
            preserve_default=False,
        ),
    ]
