# Generated by Django 2.1.4 on 2019-01-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
