# Generated by Django 2.1.4 on 2019-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='divslug',
            field=models.SlugField(default='hi', verbose_name='djangodbmodelsfieldsrelatedforeignkey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='hi', verbose_name='djangodbmodelsfieldscharfield'),
            preserve_default=False,
        ),
    ]
