# Generated by Django 2.1.4 on 2019-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20190115_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='divslug',
            field=models.SlugField(default='djangodbmodelsfieldsrelatedforeignkey'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
