# Generated by Django 2.1.4 on 2019-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20190115_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_slug',
            field=models.SlugField(default='djangodbmodelsfieldsrelatedforeignkey'),
        ),
    ]
