# Generated by Django 2.1.4 on 2019-01-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20190115_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_slug',
            field=models.SlugField(default='none'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
