# Generated by Django 2.1.4 on 2019-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20190115_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
