# Generated by Django 2.1.5 on 2019-01-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='list_date',
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
