# Generated by Django 2.1.4 on 2019-01-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='currentMatchday',
            field=models.IntegerField(null=True),
        ),
    ]
